### ISSUE TITLE
Align unbundled GitHub workflow with how Boost is built for vsomeip

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-transport-vsomeip-rust#38]
It _seems_ like Boost may be being built for Ubuntu 20.04, but they're still using ubuntu-latest, reference [here](https://github.com/COVESA/vsomeip/blob/555b980e9f56692ace840a80059c1a9d9b08439a/.github/workflows/c-cpp.yml#L9-L22):

```
jobs:
  build_on_ubuntu_boost_183_gcc_x86:
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu - Install boost 1.83.0 with gcc and x86
        uses: MarkusJx/install-boost@v2.4.4
        id: ubuntu-gcc-1_83-x86
        with:
          boost_version: 1.83.0
          platform_version: 20.04
          boost_install_dir: /home/runner
          toolset: gcc
          arch: x86
          cache: true
```

Related to #37, a more permanent fix
